spring:
  profiles:
    active: local

---

spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/notification
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

spring.profiles.include: information


---

spring.profiles: real1
spring.profiles.include: real-db, information

server:
  port: 8081

---

spring.profiles: real2
spring.profiles.include: real-db, information

server:
  port: 8082